python cor-fem.py \
--task prostate   \
--young 100 \
--bidirectional  \
--w-t2s 1.0   \
--w-s2t 1.0 \
--tangent-weight-start 0.70 \
--tangent-weight 0.22 \
--surface-smooth-k 0.8 \
--cover-dist-start 4.0 \
--cover-dist-end 12.0 \
--vol-preserve-k 5.0 \
--vol-barrier-k 25.0 \
--max-delta-u 1.0   \
--trim-normal-cos 0.15
